export {createElement} from './createElement';
export {renderElement} from './renderElement';
export {removeElement} from './removeElement';
export {replaceElement} from './replaceElement';
export {getClass} from './getClass';
export {getDate, getFullDate, getRelativeDate, getDuration} from './getDateTime';
export {getFilmControlsData} from './getFilmControlsData';
export {getPlurals} from './getPlurals';
export {getListAsStr} from './getListAsStr';
export {getFilmsByFilter} from './getFilmsByFilter';
export {sortByRating, sortByDate, sortByComments, getFilmsSortedByProp} from './sort';
export {getHandlerWithProp} from './getHandlerWithProp';
export {getHandlerWithValue} from './getHandlerWithValue';
export {getRandomID} from './getRandomID';
export {getWatched, getTotalDuration, getWatchedByGenre, getUserStatus, getWatchedByPeriod} from './stats';
