export { createElement, renderElement, removeElement, replaceElement} from './dom';
export {getClass} from './get-class';
export { getDate, getFullDate, getRelativeDate, getDuration } from './date-time';
export {getPlurals} from './get-plurals';
export {getListAsStr} from './get-list-as-str';
export {getFilmsByFilter} from './get-films-by-filter';
export {sortByRating, sortByDate, sortByComments, getFilmsSortedByProp} from './sort';
export { getHandlerWithProp, getHandlerWithValue, getHandlerToggleClass} from './handlers';
export {getWatched, getTotalDuration, getWatchedByGenre, getUserStatus, getWatchedByPeriod} from './stats';
export {shake} from './shake';
